//-----------------------------------------------------------------------
// <copyright file="ImageManifest.cs" company="Ollon, LLC">
//     Copyright (c) 2017 Ollon, LLC. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014", IsNullable=false)]
public partial class ImageManifest {
    
    /// <remarks/>
    [XmlArrayItem("Guid", typeof(ImageManifestGuid), IsNullable=false)]
    [XmlArrayItem("ID", typeof(ImageManifestID), IsNullable=false)]
    [XmlArrayItem("Import", typeof(ImageManifestImport), IsNullable=false)]
    [XmlArrayItem("String", typeof(ImageManifestString), IsNullable=false)]
    public object[] Symbols;
    
    /// <remarks/>
    [XmlArrayItem("Image", IsNullable=false)]
    public ImageManifestImage[] Images;
    
    /// <remarks/>
    [XmlArrayItem("ImageList", IsNullable=false)]
    public ImageManifestImageList[] ImageLists;
    
    /// <remarks/>
    [XmlAttribute]
    public string PackageGuid;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestGuid {
    
    /// <remarks/>
    [XmlAttribute]
    public string Name;
    
    /// <remarks/>
    [XmlAttribute]
    public string Value;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestID {
    
    /// <remarks/>
    [XmlAttribute]
    public string Name;
    
    /// <remarks/>
    [XmlAttribute]
    public int Value;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImport {
    
    /// <remarks/>
    [XmlAttribute]
    public string Manifest;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestString {
    
    /// <remarks/>
    [XmlAttribute]
    public string Name;
    
    /// <remarks/>
    [XmlAttribute]
    public string Value;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImage {
    
    /// <remarks/>
    [XmlElement("Source")]
    public ImageManifestImageSource[] Source;
    
    /// <remarks/>
    [XmlAttribute]
    public string Guid;
    
    /// <remarks/>
    [XmlAttribute]
    public string ID;
    
    /// <remarks/>
    [XmlAttribute]
    public bool AllowColorInversion;
    
    /// <remarks/>
    [XmlIgnore]
    public bool AllowColorInversionSpecified;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImageSource {
    
    /// <remarks/>
    [XmlElement("DimensionRange", typeof(ImageManifestImageSourceDimensionRange))]
    [XmlElement("Dimensions", typeof(ImageManifestImageSourceDimensions))]
    [XmlElement("Size", typeof(ImageManifestImageSourceSize))]
    [XmlElement("SizeRange", typeof(ImageManifestImageSourceSizeRange))]
    public object Item;
    
    /// <remarks/>
    public ImageManifestImageSourceNativeResource NativeResource;
    
    /// <remarks/>
    [XmlAttribute]
    public string Uri;
    
    /// <remarks/>
    [XmlAttribute]
    public ST_SourceBackgroundType Background;
    
    /// <remarks/>
    [XmlIgnore]
    public bool BackgroundSpecified;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImageSourceDimensionRange {
    
    /// <remarks/>
    [XmlAttribute]
    public int MinWidth;
    
    /// <remarks/>
    [XmlAttribute]
    public int MinHeight;
    
    /// <remarks/>
    [XmlAttribute]
    public int MaxWidth;
    
    /// <remarks/>
    [XmlAttribute]
    public int MaxHeight;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImageSourceDimensions {
    
    /// <remarks/>
    [XmlAttribute]
    public int Width;
    
    /// <remarks/>
    [XmlAttribute]
    public int Height;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImageSourceSize {
    
    /// <remarks/>
    [XmlAttribute]
    public int Value;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImageSourceSizeRange {
    
    /// <remarks/>
    [XmlAttribute]
    public int MinSize;
    
    /// <remarks/>
    [XmlAttribute]
    public int MaxSize;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImageSourceNativeResource {
    
    /// <remarks/>
    [XmlAttribute]
    public string ID;
    
    /// <remarks/>
    [XmlAttribute]
    public string Type;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[XmlType(Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public enum ST_SourceBackgroundType {
    
    /// <remarks/>
    Light,
    
    /// <remarks/>
    Dark,
    
    /// <remarks/>
    HighContrast,
    
    /// <remarks/>
    HighContrastLight,
    
    /// <remarks/>
    HighContrastDark,
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImageList {
    
    /// <remarks/>
    [XmlElement("ContainedImage")]
    public ImageManifestImageListContainedImage[] ContainedImage;
    
    /// <remarks/>
    [XmlAttribute]
    public string Guid;
    
    /// <remarks/>
    [XmlAttribute]
    public string ID;
}

/// <remarks/>
[GeneratedCode("xsd", "4.6.1055.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/ImageManifestSchema/2014")]
public partial class ImageManifestImageListContainedImage {
    
    /// <remarks/>
    [XmlAttribute]
    public string Guid;
    
    /// <remarks/>
    [XmlAttribute]
    public string ID;
    
    /// <remarks/>
    [XmlAttribute]
    public bool External;
    
    /// <remarks/>
    [XmlIgnore]
    public bool ExternalSpecified;
}
